import os
from supabase import create_client, Client
from dotenv import load_dotenv

load_dotenv()

url: str = os.environ.get('SUPABASE_URL', '')
key: str = os.environ.get('SUPABASE_KEY', '')
if not url or not key:
    print('No supabase URL/KEY. Exiting.')
    exit(1)
supabase: Client = create_client(url, key)

PROBLEMS = [
    {"title": "Add Two Numbers", "description": "Given two numbers a and b, return their sum.", "concept": "basic_syntax", "difficulty": "easy", "hints": ["Use the + operator."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "1, 2", "expected_output": "3"}, {"input": "-1, 1", "expected_output": "0"}, {"input": "0, 0", "expected_output": "0"}]},
    {"title": "Multiply Two Numbers", "description": "Given two numbers, return their product.", "concept": "basic_syntax", "difficulty": "easy", "hints": ["Use the * operator."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "2, 3", "expected_output": "6"}, {"input": "-2, 3", "expected_output": "-6"}, {"input": "0, 100", "expected_output": "0"}]},
    {"title": "Max of Three", "description": "Given three numbers, return the maximum.", "concept": "basic_syntax", "difficulty": "medium", "hints": ["Use the max() function."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "1, 2, 3", "expected_output": "3"}, {"input": "-1, -5, -2", "expected_output": "-1"}, {"input": "0, 0, 0", "expected_output": "0"}]},
    {"title": "Is Even", "description": "Given a number, return True if even, False otherwise.", "concept": "basic_syntax", "difficulty": "medium", "hints": ["Use the modulo operator %."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "2", "expected_output": "True"}, {"input": "3", "expected_output": "False"}, {"input": "0", "expected_output": "True"}]},
    {"title": "FizzBuzz Single", "description": "Given n, return 'Fizz' if divisible by 3, 'Buzz' if by 5, 'FizzBuzz' if both, else the string of n.", "concept": "basic_syntax", "difficulty": "hard", "hints": ["Check modulo 15 first."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "3", "expected_output": "Fizz"}, {"input": "5", "expected_output": "Buzz"}, {"input": "15", "expected_output": "FizzBuzz"}]},
    {"title": "Sum of N", "description": "Given n, return sum from 1 to n.", "concept": "loops", "difficulty": "easy", "hints": ["Use a for loop."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "5", "expected_output": "15"}, {"input": "1", "expected_output": "1"}, {"input": "10", "expected_output": "55"}]},
    {"title": "Factorial", "description": "Return n! (n factorial).", "concept": "loops", "difficulty": "easy", "hints": ["Use a while or for loop."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "5", "expected_output": "120"}, {"input": "0", "expected_output": "1"}, {"input": "3", "expected_output": "6"}]},
    {"title": "Print Squares", "description": "Given n, return a list of squares from 0 to n-1.", "concept": "loops", "difficulty": "medium", "hints": ["Use list comprehension."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "3", "expected_output": "[0, 1, 4]"}, {"input": "1", "expected_output": "[0]"}, {"input": "5", "expected_output": "[0, 1, 4, 9, 16]"}]},
    {"title": "Count Vowels", "description": "Given a string, return the number of vowels.", "concept": "loops", "difficulty": "medium", "hints": ["Iterate through characters."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "'hello'", "expected_output": "2"}, {"input": "'apple'", "expected_output": "2"}, {"input": "'bcd'", "expected_output": "0"}]},
    {"title": "Prime Check", "description": "Return True if n is prime, False otherwise.", "concept": "loops", "difficulty": "hard", "hints": ["Iterate up to sqrt(n)."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "2", "expected_output": "True"}, {"input": "4", "expected_output": "False"}, {"input": "17", "expected_output": "True"}]},
    {"title": "Find Max", "description": "Find the maximum element in a list.", "concept": "arrays", "difficulty": "easy", "hints": ["Use max() or loop."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[1, 2, 3]", "expected_output": "3"}, {"input": "[-1, -2]", "expected_output": "-1"}, {"input": "[5]", "expected_output": "5"}]},
    {"title": "Reverse Array", "description": "Return the reversed list.", "concept": "arrays", "difficulty": "easy", "hints": ["Use [::-1]."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[1, 2]", "expected_output": "[2, 1]"}, {"input": "[]", "expected_output": "[]"}, {"input": "[5, 4, 3]", "expected_output": "[3, 4, 5]"}]},
    {"title": "Remove Duplicates", "description": "Remove duplicates from array, return length.", "concept": "arrays", "difficulty": "medium", "hints": ["Use a set."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[1, 1, 2]", "expected_output": "2"}, {"input": "[1, 2, 3]", "expected_output": "3"}, {"input": "[1, 1, 1, 1]", "expected_output": "1"}]},
    {"title": "Move Zeroes", "description": "Move all zeroes to the end, maintain order. Return array.", "concept": "arrays", "difficulty": "medium", "hints": ["Count zeroes and filter."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[0, 1, 0, 3]", "expected_output": "[1, 3, 0, 0]"}, {"input": "[0]", "expected_output": "[0]"}, {"input": "[1, 2]", "expected_output": "[1, 2]"}]},
    {"title": "Merge Sorted Arrays", "description": "Merge two sorted arrays into one sorted array.", "concept": "arrays", "difficulty": "hard", "hints": ["Use two pointers."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[1, 3], [2, 4]", "expected_output": "[1, 2, 3, 4]"}, {"input": "[], [1]", "expected_output": "[1]"}, {"input": "[2], [1]", "expected_output": "[1, 2]"}]},
    {"title": "Palindrome Check", "description": "Return True if string is a palindrome.", "concept": "strings", "difficulty": "easy", "hints": ["Compare string to its reverse."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "'racecar'", "expected_output": "True"}, {"input": "'hello'", "expected_output": "False"}, {"input": "'a'", "expected_output": "True"}]},
    {"title": "Valid Anagram", "description": "Return True if s and t are anagrams.", "concept": "strings", "difficulty": "easy", "hints": ["Compare character counts."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "'anagram', 'nagaram'", "expected_output": "True"}, {"input": "'rat', 'car'", "expected_output": "False"}, {"input": "'a', 'a'", "expected_output": "True"}]},
    {"title": "Longest Common Prefix", "description": "Find longest common prefix in array of strings.", "concept": "strings", "difficulty": "medium", "hints": ["Compare character by character."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "['flower','flow','flight']", "expected_output": "fl"}, {"input": "['dog','racecar','car']", "expected_output": ""}, {"input": "['a']", "expected_output": "a"}]},
    {"title": "String Compression", "description": "Compress string using counts of repeated characters.", "concept": "strings", "difficulty": "medium", "hints": ["Iterate and count consecutive characters."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "'aabbb'", "expected_output": "a2b3"}, {"input": "'a'", "expected_output": "a1"}, {"input": "'aa'", "expected_output": "a2"}]},
    {"title": "Longest Substring Without Repeating Characters", "description": "Find length of longest substring without repeats.", "concept": "strings", "difficulty": "hard", "hints": ["Use sliding window."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "'abcabcbb'", "expected_output": "3"}, {"input": "'bbbbb'", "expected_output": "1"}, {"input": "'pwwkew'", "expected_output": "3"}]},
    {"title": "Two Sum", "description": "Find indices of two numbers that add up to target.", "concept": "hashing", "difficulty": "easy", "hints": ["Use a hash map."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[2,7,11,15], 9", "expected_output": "[0, 1]"}, {"input": "[3,2,4], 6", "expected_output": "[1, 2]"}, {"input": "[3,3], 6", "expected_output": "[0, 1]"}]},
    {"title": "Contains Duplicate", "description": "Return True if any value appears at least twice.", "concept": "hashing", "difficulty": "easy", "hints": ["Use a set."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[1,2,3,1]", "expected_output": "True"}, {"input": "[1,2,3,4]", "expected_output": "False"}, {"input": "[1,1,1,3,3,4,3,2,4,2]", "expected_output": "True"}]},
    {"title": "Group Anagrams", "description": "Group anagrams together.", "concept": "hashing", "difficulty": "medium", "hints": ["Sort each string to use as key."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "['eat','tea','tan','ate','nat','bat']", "expected_output": "[['eat','tea','ate'],['tan','nat'],['bat']]"}, {"input": "['']", "expected_output": "[['']]"}, {"input": "['a']", "expected_output": "[['a']]"}]},
    {"title": "Intersection of Two Arrays", "description": "Return their intersection.", "concept": "hashing", "difficulty": "medium", "hints": ["Use sets."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[1,2,2,1], [2,2]", "expected_output": "[2]"}, {"input": "[4,9,5], [9,4,9,8,4]", "expected_output": "[9, 4]"}, {"input": "[1], [1]", "expected_output": "[1]"}]},
    {"title": "Subarray Sum Equals K", "description": "Find total number of continuous subarrays whose sum equals k.", "concept": "hashing", "difficulty": "hard", "hints": ["Use prefix sum and hash map."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[1,1,1], 2", "expected_output": "2"}, {"input": "[1,2,3], 3", "expected_output": "2"}, {"input": "[1,-1,0], 0", "expected_output": "3"}]},
    {"title": "Valid Palindrome", "description": "Check if string is palindrome considering only alphanumeric chars.", "concept": "two_pointers", "difficulty": "easy", "hints": ["Use left and right pointers."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "'A man, a plan, a canal: Panama'", "expected_output": "True"}, {"input": "'race a car'", "expected_output": "False"}, {"input": "' '", "expected_output": "True"}]},
    {"title": "Reverse String", "description": "Reverse string in place.", "concept": "two_pointers", "difficulty": "easy", "hints": ["Swap left and right pointers."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "['h','e','l','l','o']", "expected_output": "['o','l','l','e','h']"}, {"input": "['H','a','n','n','a','h']", "expected_output": "['h','a','n','n','a','H']"}, {"input": "['a']", "expected_output": "['a']"}]},
    {"title": "Container With Most Water", "description": "Find two lines that together with x-axis forms container with most water.", "concept": "two_pointers", "difficulty": "medium", "hints": ["Move the shorter line's pointer."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[1,8,6,2,5,4,8,3,7]", "expected_output": "49"}, {"input": "[1,1]", "expected_output": "1"}, {"input": "[4,3,2,1,4]", "expected_output": "16"}]},
    {"title": "Three Sum", "description": "Find all unique triplets that sum to 0.", "concept": "two_pointers", "difficulty": "medium", "hints": ["Sort then use two pointers."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[-1,0,1,2,-1,-4]", "expected_output": "[[-1, -1, 2], [-1, 0, 1]]"}, {"input": "[]", "expected_output": "[]"}, {"input": "[0]", "expected_output": "[]"}]},
    {"title": "Trapping Rain Water", "description": "Compute how much water can be trapped after raining.", "concept": "two_pointers", "difficulty": "hard", "hints": ["Use two pointers from edges."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[0,1,0,2,1,0,1,3,2,1,2,1]", "expected_output": "6"}, {"input": "[4,2,0,3,2,5]", "expected_output": "9"}, {"input": "[1,0,1]", "expected_output": "1"}]},
    {"title": "Maximum Average Subarray I", "description": "Find contiguous subarray of length k with max average.", "concept": "sliding_window", "difficulty": "easy", "hints": ["Maintain sum of window."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[1,12,-5,-6,50,3], 4", "expected_output": "12.75"}, {"input": "[5], 1", "expected_output": "5.0"}, {"input": "[0,4,0,3,2], 1", "expected_output": "4.0"}]},
    {"title": "Contains Duplicate II", "description": "Check if there are duplicate values within distance k.", "concept": "sliding_window", "difficulty": "easy", "hints": ["Use a set of size k."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[1,2,3,1], 3", "expected_output": "True"}, {"input": "[1,0,1,1], 1", "expected_output": "True"}, {"input": "[1,2,3,1,2,3], 2", "expected_output": "False"}]},
    {"title": "Longest Repeating Character Replacement", "description": "Find longest substring of same letter with k replacements.", "concept": "sliding_window", "difficulty": "medium", "hints": ["Track counts in window."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "'ABAB', 2", "expected_output": "4"}, {"input": "'AABABBA', 1", "expected_output": "4"}, {"input": "'A', 0", "expected_output": "1"}]},
    {"title": "Permutation in String", "description": "Check if s2 contains a permutation of s1.", "concept": "sliding_window", "difficulty": "medium", "hints": ["Use fixed window and char counts."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "'ab', 'eidbaooo'", "expected_output": "True"}, {"input": "'ab', 'eidboaoo'", "expected_output": "False"}, {"input": "'a', 'a'", "expected_output": "True"}]},
    {"title": "Minimum Window Substring", "description": "Find minimum window in s containing all chars of t.", "concept": "sliding_window", "difficulty": "hard", "hints": ["Expand right, shrink left."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "'ADOBECODEBANC', 'ABC'", "expected_output": "BANC"}, {"input": "'a', 'a'", "expected_output": "a"}, {"input": "'a', 'aa'", "expected_output": ""}]},
    {"title": "Fibonacci Number", "description": "Return n-th Fibonacci number.", "concept": "recursion", "difficulty": "easy", "hints": ["Base cases 0 and 1."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "2", "expected_output": "1"}, {"input": "3", "expected_output": "2"}, {"input": "4", "expected_output": "3"}]},
    {"title": "Power of Two", "description": "Check if n is a power of two.", "concept": "recursion", "difficulty": "easy", "hints": ["Recursively divide by 2."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "1", "expected_output": "True"}, {"input": "16", "expected_output": "True"}, {"input": "3", "expected_output": "False"}]},
    {"title": "Pow(x, n)", "description": "Calculate x raised to power n.", "concept": "recursion", "difficulty": "medium", "hints": ["Use fast exponentiation."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "2.00000, 10", "expected_output": "1024.0"}, {"input": "2.10000, 3", "expected_output": "9.261"}, {"input": "2.00000, -2", "expected_output": "0.25"}]},
    {"title": "K-th Symbol in Grammar", "description": "Find k-th symbol in n-th row of a specific grammar.", "concept": "recursion", "difficulty": "medium", "hints": ["Relate k to k/2."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "1, 1", "expected_output": "0"}, {"input": "2, 1", "expected_output": "0"}, {"input": "2, 2", "expected_output": "1"}]},
    {"title": "Regular Expression Matching", "description": "Implement regex matching with . and *.", "concept": "recursion", "difficulty": "hard", "hints": ["Handle * by matching 0 or 1+ times."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "'aa', 'a'", "expected_output": "False"}, {"input": "'aa', 'a*'", "expected_output": "True"}, {"input": "'ab', '.*'", "expected_output": "True"}]},
    {"title": "Binary Watch", "description": "Return all possible times for n LEDs on a binary watch.", "concept": "backtracking", "difficulty": "easy", "hints": ["Iterate through all 1024 combinations."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "1", "expected_output": "['0:01', '0:02', '0:04', '0:08', '0:16', '0:32', '1:00', '2:00', '4:00', '8:00']"}, {"input": "0", "expected_output": "['0:00']"}, {"input": "9", "expected_output": "[]"}]},
    {"title": "Sum of All Subset XOR Totals", "description": "Return sum of all XOR totals for every subset.", "concept": "backtracking", "difficulty": "easy", "hints": ["Backtrack include/exclude."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[1,3]", "expected_output": "6"}, {"input": "[5,1,6]", "expected_output": "28"}, {"input": "[3,4,5,6,7,8]", "expected_output": "480"}]},
    {"title": "Permutations", "description": "Return all possible permutations of an array.", "concept": "backtracking", "difficulty": "medium", "hints": ["Swap elements and recurse."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[1,2,3]", "expected_output": "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]"}, {"input": "[0,1]", "expected_output": "[[0,1],[1,0]]"}, {"input": "[1]", "expected_output": "[[1]]"}]},
    {"title": "Combinations", "description": "Return all combinations of k numbers out of 1 to n.", "concept": "backtracking", "difficulty": "medium", "hints": ["Backtrack to build combinations."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "4, 2", "expected_output": "[[1,2],[1,3],[1,4],[2,3],[2,4],[3,4]]"}, {"input": "1, 1", "expected_output": "[[1]]"}, {"input": "3, 3", "expected_output": "[[1,2,3]]"}]},
    {"title": "N-Queens", "description": "Solve N-Queens puzzle, return all valid board configurations.", "concept": "backtracking", "difficulty": "hard", "hints": ["Track columns and diagonals."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "4", "expected_output": "[['.Q..','...Q','Q...','..Q.'],['..Q.','Q...','...Q','.Q..']]"}, {"input": "1", "expected_output": "[['Q']]"}, {"input": "2", "expected_output": "[]"}]},
    {"title": "Binary Search", "description": "Find target in sorted array, return index or -1.", "concept": "binary_search", "difficulty": "easy", "hints": ["Check middle element."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[-1,0,3,5,9,12], 9", "expected_output": "4"}, {"input": "[-1,0,3,5,9,12], 2", "expected_output": "-1"}, {"input": "[5], 5", "expected_output": "0"}]},
    {"title": "Search Insert Position", "description": "Find insert position for target in sorted array.", "concept": "binary_search", "difficulty": "easy", "hints": ["Binary search for insertion point."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[1,3,5,6], 5", "expected_output": "2"}, {"input": "[1,3,5,6], 2", "expected_output": "1"}, {"input": "[1,3,5,6], 7", "expected_output": "4"}]},
    {"title": "Search in Rotated Sorted Array", "description": "Find target in rotated sorted array.", "concept": "binary_search", "difficulty": "medium", "hints": ["Check which half is sorted."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[4,5,6,7,0,1,2], 0", "expected_output": "4"}, {"input": "[4,5,6,7,0,1,2], 3", "expected_output": "-1"}, {"input": "[1], 0", "expected_output": "-1"}]},
    {"title": "Find Minimum in Rotated Sorted Array", "description": "Find minimum element in rotated array.", "concept": "binary_search", "difficulty": "medium", "hints": ["Compare mid with right pointer."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[3,4,5,1,2]", "expected_output": "1"}, {"input": "[4,5,6,7,0,1,2]", "expected_output": "0"}, {"input": "[11,13,15,17]", "expected_output": "11"}]},
    {"title": "Median of Two Sorted Arrays", "description": "Find median of two sorted arrays.", "concept": "binary_search", "difficulty": "hard", "hints": ["Binary search on smaller array."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[1,3], [2]", "expected_output": "2.0"}, {"input": "[1,2], [3,4]", "expected_output": "2.5"}, {"input": "[], [1]", "expected_output": "1.0"}]},
    {"title": "Maximum Depth of Binary Tree", "description": "Return max depth of binary tree.", "concept": "trees", "difficulty": "easy", "hints": ["Recursively find max depth of children."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[3,9,20,None,None,15,7]", "expected_output": "3"}, {"input": "[1,None,2]", "expected_output": "2"}, {"input": "[]", "expected_output": "0"}]},
    {"title": "Invert Binary Tree", "description": "Invert a binary tree.", "concept": "trees", "difficulty": "easy", "hints": ["Swap left and right children."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[4,2,7,1,3,6,9]", "expected_output": "[4,7,2,9,6,3,1]"}, {"input": "[2,1,3]", "expected_output": "[2,3,1]"}, {"input": "[]", "expected_output": "[]"}]},
    {"title": "Lowest Common Ancestor of BST", "description": "Find LCA of two nodes in BST.", "concept": "trees", "difficulty": "medium", "hints": ["Use BST property."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[6,2,8,0,4,7,9,None,None,3,5], 2, 8", "expected_output": "6"}, {"input": "[6,2,8,0,4,7,9,None,None,3,5], 2, 4", "expected_output": "2"}, {"input": "[2,1], 2, 1", "expected_output": "2"}]},
    {"title": "Binary Tree Level Order Traversal", "description": "Return level order traversal of nodes' values.", "concept": "trees", "difficulty": "medium", "hints": ["Use a queue (BFS)."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[3,9,20,None,None,15,7]", "expected_output": "[[3],[9,20],[15,7]]"}, {"input": "[1]", "expected_output": "[[1]]"}, {"input": "[]", "expected_output": "[]"}]},
    {"title": "Serialize and Deserialize Binary Tree", "description": "Design an algorithm to serialize/deserialize a binary tree.", "concept": "trees", "difficulty": "hard", "hints": ["Use pre-order or level-order."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[1,2,3,None,None,4,5]", "expected_output": "[1,2,3,None,None,4,5]"}, {"input": "[]", "expected_output": "[]"}, {"input": "[1]", "expected_output": "[1]"}]},
    {"title": "Climbing Stairs", "description": "Find distinct ways to climb n steps (1 or 2 at a time).", "concept": "dynamic_programming", "difficulty": "easy", "hints": ["Fibonacci sequence."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "2", "expected_output": "2"}, {"input": "3", "expected_output": "3"}, {"input": "4", "expected_output": "5"}]},
    {"title": "Min Cost Climbing Stairs", "description": "Find min cost to reach top of floor.", "concept": "dynamic_programming", "difficulty": "easy", "hints": ["dp[i] = cost[i] + min(dp[i-1], dp[i-2])."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[10,15,20]", "expected_output": "15"}, {"input": "[1,100,1,1,1,100,1,1,100,1]", "expected_output": "6"}, {"input": "[0,0,0,0]", "expected_output": "0"}]},
    {"title": "Coin Change", "description": "Find min coins to make amount.", "concept": "dynamic_programming", "difficulty": "medium", "hints": ["Bottom-up DP."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[1,2,5], 11", "expected_output": "3"}, {"input": "[2], 3", "expected_output": "-1"}, {"input": "[1], 0", "expected_output": "0"}]},
    {"title": "Longest Increasing Subsequence", "description": "Find length of LIS.", "concept": "dynamic_programming", "difficulty": "medium", "hints": ["dp[i] = max(dp[j] + 1) for j < i."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "[10,9,2,5,3,7,101,18]", "expected_output": "4"}, {"input": "[0,1,0,3,2,3]", "expected_output": "4"}, {"input": "[7,7,7,7,7,7,7]", "expected_output": "1"}]},
    {"title": "Edit Distance", "description": "Min operations to convert word1 to word2.", "concept": "dynamic_programming", "difficulty": "hard", "hints": ["2D DP array."], "starter_code": {"python": "def solve():\n    pass"}, "test_cases": [{"input": "'horse', 'ros'", "expected_output": "3"}, {"input": "'intention', 'execution'", "expected_output": "5"}, {"input": "'', ''", "expected_output": "0"}]},

]

def seed():
    # clear existing
    supabase.table('problems').delete().neq('problem_id', '00000000-0000-0000-0000-000000000000').execute()
    res = supabase.table('problems').insert(PROBLEMS).execute()
    print(f'Seeded {len(res.data)} problems.')

if __name__ == '__main__':
    seed()
